\-- Test 'require'
\require test/lib\--
$a
\-- Result
27
\-- End

\-- Test 'require (file does not exit)'
\require foo
\-- Error
File 'string', line 1 : File 'foo' doesn't exist or cannot be read.
Tried: 
    foo.lua
    foo/init.lua

    \require foo
             ^^^
Traceback :
    File 'string', line 1 : \require foo
                            ^^^^^^^^
\-- End

\-- Test 'include'
\include test/lib.plume\--
\double foo
\-- Result
foo foo
\-- End

\-- Test 'include with params'
\include[x=bar] test/lib.plume\--
\foo
\-- Result
x = bar
\-- End

\-- Test 'include extern'
\extern test/lib.plume
\-- Result
\def double[x] {$x $x}\--

\def foo {x = ${__file_params.x}}
\-- End

\-- Test 'include error'
\include test/lib_error.plume
\-- Error
File 'test/lib_error.plume', line 1 : Unknow macro 'foo'. Perhaps you mean 'do' or 'for'?
    \foo
    ^^^^
Traceback :
    File 'string', line 1 : \include test/lib_error.plume
                            ^^^^^^^^
\-- End

\-- Test 'Error in extern file'
\require test/lib
${foo()} 
\-- Error Lua 5.1 Lua 5.2
File 'test/lib.lua', line 4 : (lua error) attempt to perform arithmetic on global 'b' (a nil value)
    return b+1
    ^^^^^^^^^^^
Traceback :
    File 'string', line 2 : ${foo()} 
                             ^^^^^^^
\-- End

\-- Test 'Error in extern file'
\require test/lib
${foo()} 
\-- Error Lua 5.3 Lua 5.4
File 'test/lib.lua', line 4 : (lua error) attempt to perform arithmetic on a nil value (global 'b')
    return b+1
    ^^^^^^^^^^^
Traceback :
    File 'string', line 2 : ${foo()} 
                             ^^^^^^^
\-- End